### ISSUE TITLE
Visual Referee

### ISSUE THREAD

**Issue by oleflb** [HULKs/hulk#658] opened 2023-12-21 17:31 UTC
In the new roles, the transition Initial -> Ready is now indicated by a visual referee sign. If we miss the visual sign we have an effective time penalty of 30s.
We need a way to detect the visual sign, probably by using a neural network.

**Comment by knoellle** [comment] 2024-04-16 20:21
Duplicate of #549

**Closed by knoellle** 2024-04-16 20:21 UTC
Labels: cat:MachineLearning, cat:Vision, rules:2024, GO24
