### ISSUE TITLE
Speed up stand up motions

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#485] opened 2023-07-07 17:27 UTC
Our current stand up motions are alright, but still noticeably slower than other team's.
For a start, one can simply decrease the duration of select keyframes, mainly the last couple ones, to gain roughly a second or so.

**Comment by MaikRe** [comment] 2024-04-20 22:02
Duplicate of #542

**Comment by schluis** [comment] 2024-04-21 08:18
The idea of this issue is to decrease the speed of current motions by reducing the duraiton of keyframes, while #542 aims at using completely new motions.

**Closed** 2024-05-30 00:13 UTC
Labels: cat:Motion
