### ISSUE TITLE
Use penalize messages to other team to block Initial to Ready transition

### ISSUE THREAD

**Issue by ThagonDuarte** [HULKs/hulk#982] opened 2024-05-01 09:50 UTC
Listen for penalize messages for Motion in Initial to the other team. In such a case, the visual referee signal has surely not happened yet, and the transition to Ready can safely be blocked for a certain duration.

**Comment by MaikRe** [comment] 2024-06-19 10:00
Duplicate of #877

**Closed by MaikRe** 2024-06-19 10:00 UTC
