### ISSUE TITLE
Tweak kick decision reach

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#308] opened 2023-04-29 18:17 UTC
Tweak the "kick decision reach" parameter to increase kick accuracy in a few cases.
Ask @h3ndrk for details.

**Comment by knoellle** [comment] 2023-07-19 12:49
Too little information, I assume this means to tighten the thresholds when we have time to position ourselves for a more accurate kick.
If that's what was meant, I think that's a hack and we shouldn't do that. We should rather try to find the root cause for why we need these large thresholds in the first place and reduce jockeln that way instead.
We could also try to go the other way and calculate a foot trajectory for moving the ball where we want it to go instead of trying to find thresholds for a static, "good enough" kick position.

**Comment by knoellle** [comment] 2024-04-20 18:55
Fixed by #951

**Closed by knoellle** 2024-04-20 18:55 UTC
Labels: cat:MotionPlanning
