### ISSUE TITLE
Prevent behavior from walking into the opponents' half

### ISSUE THREAD

**Issue by MeiiMoon** [HULKs/hulk#1302] opened 2024-07-17 14:05 UTC
What? 
The robots sometime run into the opponents' half. So we could test that specific scenario in behavior simulator and find ways to fix this problem. 

Why? 
If this is fixed, it would save us some penalties.

**Comment by MaikRe** [comment] 2024-07-17 18:04
Solved by #1307,  duplicate of #1287

**Closed by MaikRe** 2024-07-17 18:04 UTC
