### ISSUE TITLE
Corner kicks are too powerful

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#285] opened 2023-04-29 09:24 UTC
During today's game against Naova, a robot executed a corner kick with way too much force such that the ball left the field on the other side.

**Comment by julianschuler** [comment] 2023-05-08 15:12
With the current walking parameters I am unable to reproduce this at the SMD. I am closing this in favor of #334 which considers kicking strength in general.

**Closed by julianschuler** 2023-05-08 15:12 UTC
Labels: cat:Behavior
