### ISSUE TITLE
Investigate robots not respecting ball is free

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#244] opened 2023-04-27 15:41 UTC
In the game against Bembelbots today, we have multiple robots enter the center circle before the ball was free during an opponent kick off.

**Comment by schmidma** [comment] 2023-04-29 10:42
@MaikRe checked, everything should be fine, the referee has some delay ;)

**Comment by Narcha** [comment] 2023-07-08 17:20
This occurred again on multiple occasions today and yesterday.

**Comment by okiwi6** [comment] 2023-11-22 08:12
Duplicate of #593

**Closed by okiwi6** 2023-11-22 08:12 UTC
Labels: cat:Behavior
